on:
  pull_request:
    branches:
      - '*'
  push:
    branches:
      - '*'
      - '!live'

name: Test

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v2

      - name: Cache node_modules
        uses: actions/cache@v1
        with:
          path: node_modules
          key: ${{ runner.os }}-node_modules-${{ hashFiles('**/yarn.lock') }}

      - run: npm install
      - run: npm run build
        env:
          CI: false
          GENERATE_SOURCEMAP: false